# Generated by Django 5.1.1 on 2025-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_approvedrestaurant_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedrestaurant',
            name='halal',
            field=models.BooleanField(default=False, verbose_name='Halal'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='halal',
            field=models.BooleanField(default=False, verbose_name='Halal'),
        ),
    ]
