# Generated by Django 5.1.1 on 2025-04-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_approvedrestaurant_halal_restaurant_halal'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedrestaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='approved_restaurant_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/', verbose_name='Image'),
        ),
    ]
