# Generated by Django 5.1.1 on 2025-04-15 11:46

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_approvedrestaurant_image_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedrestaurant',
            name='image',
            field=models.ImageField(blank=True, default=restaurant.models.get_default_restaurant_image, null=True, upload_to='approved_restaurant_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default=restaurant.models.get_default_restaurant_image, null=True, upload_to='restaurant_images/', verbose_name='Image'),
        ),
    ]
