# Generated by Django 5.1.1 on 2025-04-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_city_alter_restaurant_country_and_more'),
        ('restaurant', '0005_alter_approvedrestaurant_image_and_more'),
    ]

    operations = [
    ]
